name: Deployment

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  ploi_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Ploi webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.PLOI_DEPLOY_WEBHOOK }}
